### ISSUE TITLE
Unable to patch Mother 3 translation

### ISSUE THREAD

**Issue by Limero** [Alcaro/Flips#1]
I'm unable to patch the Mother 3 translation with Flips. The error message that I get is **"This patch is not intended for this ROM."**. All patches that I've tried for other games have worked correctly. The things that I can think of that may cause this is the fact that it's a pretty big rom (33MB) or because the patch is in ups format. I haven't found any other ups patches to test with. The patches I have tried are either ips or xdelta, where all ips worked and xdelta gave an **"Unknown patch format."** error. I assume I would get the same error if ups wasn't supported at all.

The rom that I'm trying to patch is from the no-intro collection and its SHA-1 matches the recommended one at romhacking.net. I'm using Flips v1.31 installed from the AUR on Arch Linux (https://aur.archlinux.org/packages/flips/).

Link to patch: http://www.romhacking.net/translations/1333/

**Comment by Alcaro** [comment]
(Apparently I unwatched this repo and missed this issue, sorry about that)

**Comment by Alcaro** [comment]
Possible problem cause 1: The exact same issue. I no longer make releases, so there is no release containing the above fix.

Possible problem cause 2: Your ROM isn't as clean as you think. GBA has a problem with people dumping roms, and adding shitty preloaders crediting themselves before publishing the rom. Then other people take those damaged ROMs and remove the code calling the preloader, but not the preloader code itself; Flips can't see that the preloader is unused, it just sees that the input file isn't identical to the expected one. To solve that, make sure you're using the No-Intro roms.

**Comment by Europia79** [comment]
i never knew that **Flips** supports the **UPS** patching format ?

Other options for _THIS_ problem here are:
(1) The [Javascript_Patchter](https://www.romhacking.net/patch/index.php?file=translations/1333&patch_name=Mother+3+English+translation+v1.3a&crc=42AC9CB9)
(2) upset:  https://www.romhacking.net/utilities/677/
(3) NUPS:  https://www.romhacking.net/utilities/606/
(4) MultiPatch:  https://projects.sappharad.com/multipatch/
