### ISSUE TITLE
flips segfaults easily by trying to create multi-gb patches

### ISSUE THREAD

**Issue by i30817** [Alcaro/Flips#10]
The ones typically found when you try to compare a psp/p2/wii game patched and unpatched. Compared to xdelta, which takes much less memory, flips (bps) seems to have pathological memory consumption. Maybe it expected to be able to hold all of the source in memory?

I'm going to have to add another mode for my utility to deal with xdelta patches for the iso cases unless this is solved.

I used --bps-linear btw, shouldn't i have?

**Comment by Alcaro** [comment]
Yes, all patching functions like to read the entire files into memory, it's a lot easier that way. Flips is more designed for 4MB SNES ROMs than 4GB Wii ISOs.

Still, segfault is definitely wrong answer. And I can mmap the files instead of malloc, which takes a lot less memory.

**Comment by i30817** [comment]
I see. Well, i edited in my dat creator tool the ability to use xdelta for these cases then.

A question if you will, do you know if xdelta patches have the same or similar crc32 footer that bps has? That kind of spoiled me.

**Comment by i30817** [comment]
OK. I should have asked (and now did) on the xdelta github anyway.

**Comment by Alcaro** [comment]
I'll just assume you're satisfied with the fixes I made.

**Comment by i30817** [comment]
yes
