### ISSUE TITLE
OS X GUI Support branch

### ISSUE THREAD

**Issue by covarianttensor** [Alcaro/Flips#11]
I have written a qt5 GUI wrapper around Flips that runs on OS X. I am requesting your repo make a new branch for this version so I can make a pull request into it. It's not meant to be merged into master.
You can check out my fork here: https://github.com/covarianttensor/Flips/tree/osx_qt5

**Comment by Alcaro** [comment]
[Sure, why not](https://github.com/Alcaro/Flips/tree/osx_qt5)
