### ISSUE TITLE
BPM

### ISSUE THREAD

**Issue by Rus3545** [Alcaro/Flips#23]
Hi.
I saw a backup of bsnes. 
I thought maybe you still have the same collection of beat versions. 
The very first one that knew how to do bpm is interesting: 
beat_v01.tar.xz (source code + documentation)

**Comment by Screwtapello** [comment]
I happened to have an archive of byuu's old patching software, so I uploaded it to the Internet Archive: https://archive.org/download/byuus-historical-patching-tools
