### ISSUE TITLE
Exit code 3 - This patch is not intended for this ROM.

### ISSUE THREAD

**Issue by Pilzinsel64** [Alcaro/Flips#36]
Hello,

Could you implement an option to ignore this error message please? I want to apply a BPS patch anyway. The file where the patch is for has changed only minimalistic. 

I am using Flips cia CLI. I already tried the command `--ignore-checksum` but it didn't worked (or I missundertstand it).

The version I used was v1.31 and today I compiled v1.40 pre (master branche).

Thank you very much.

**Comment by Alcaro** [comment]
Looks like Flips emits your desired output file, then reports failure.

I agree that's a bug...

**Comment by Pilzinsel64** [comment]
Wow, that was fast. Thank you very muh @Alcaro!
