### ISSUE TITLE
About those firefox tars...

### ISSUE THREAD

**Issue by lochlainn** [Alcaro/Flips#40]
Just a suggestion: if you wanted to make those easily available without inflating the repo size, you could try faux-creating them into a build artifact. Maybe write a short shell script to curl them down from the public repo, then have that sit statically in your CI result? Hell, you could even put them in a release.

It's not a huge issue, but my machine took the git pull pretty hard when I updated my repo from last year, haha.

**Comment by Alcaro** [comment]
Yes, including them in the repo certainly has a few drawbacks. But so does fetching them - some CIs are sandboxed and can't access the internet.

Neither option is good. I believe this is the less bad one, but I haven't done a whole lot of research on that topic.

Ideally, I'd find something that trains Flips' PGO as well as the Firefoxes but takes less space, compresses better, or can be autogenerated from a 3KB Python script.
