### ISSUE TITLE
build broken over termux (arm, android)

### ISSUE THREAD

**Issue by foxsouns** [Alcaro/Flips#46]
im running into a clang error while attempting to compile flips. i have g++ installed, and build-essential, and this should be all, as termux repacks debian packages for its package manager (which is apt with different mirrors)
i was aiming for a cli build, and grabbed from the latest commit as of posting. im going to post the log on gist, and will post link here soon

**Comment by foxsouns** [comment]
[here](https://gist.github.com/foxsouns/2669fdfac33e55545443a6dfcfb151ca) is the link.

**Comment by Alcaro** [comment]
I've never tried Flips on Android. Doesn't surprise me if it's broken.

Try using `make CFLAGS=-O3` instead of `./make.sh`. make.sh optimizes harder, but most of those optimizations seem unavailable under this compiler anyways.

**Comment by foxsouns** [comment]
works when compiling with `make CFLAGS=-O3`. 

these 
errors makes me think that some optimizations in make.sh either may be depreciated, or arm g++ doesnt have them. either way, thank you for the help! feel free to close this if you see fit

termux is an app that tries to maintain compatibility with linux, over android. its similar to wine, but under the restrictions of host android.

**Comment by Alcaro** [comment]
That's not g++. It's clang-13, a different compiler. They try to be similar, but have a couple of odd differences in rarer features, including some of these.

Most of them seem more like Clang bugs than Flips bugs to me, so I vote closed status.

**Comment by foxsouns** [comment]
ah, i guess i didnt see that; i popped g++ in my terminal and it responded, so i thought i had it haha
