### ISSUE TITLE
This patch is not intended for this ROM Error

### ISSUE THREAD

**Issue by Marnalar** [Alcaro/Flips#51]
![image](https://user-images.githubusercontent.com/36113374/201421596-108f10a3-3c60-45db-9324-27a2e48cc097.png)
I can't patch my European SM64 version with the Super Mario Star Road .bps file.

**Comment by Alcaro** [comment]
Don't use the European SM64 version. Use the USA version. Almost all rom hacks are for the USA version.

**Comment by Marnalar** [comment]
The thing is you're right. But I want to play this on my wii u via Virtual Console you know. And I have already seen that by someone from europe who got that to work. But I don't know how he patched his ROM, he was german.
