### ISSUE TITLE
Add link to Flatpak in the readme?

### ISSUE THREAD

**Issue by MightyCreak** [Alcaro/Flips#53]
Someone made a Flatpak out of this project (maybe it's you @Alcaro ?)

I'd suggest to add this way of installing the app on Linux (as it is dumb stupid to install and compatible with any distrib with Flatpak installed).

Here's the link: https://flathub.org/apps/details/com.github.Alcaro.Flips

I'm using it myself and it works like a charm.

**Comment by Alcaro** [comment]
It's maintained by @Kekun, though I have merged a few PRs related to it.

Sure, good idea.
