### ISSUE TITLE
GNOME 42 Runtime - Not supported anymore. Flatpak

### ISSUE THREAD

**Issue by Lazorne** [Alcaro/Flips#62]
Hello we are getting a warning when using the flatpak version: 
GNOME 42 Runtime - Not supported anymore.

You probably need to upgrade to a more current runtime platform.

**Comment by Alcaro** [comment]
Yes, that's #50. I don't know anything about flatpak or flathub, so I'm not merging that until everything's done in the linked flathub pull. I don't know what that one's waiting for.

**Comment by mberlinger3** [comment]
> Yes, that's #50. I don't know anything about flatpak or flathub, so I'm not merging that until everything's done in the linked flathub pull. I don't know what that one's waiting for.

Looks like there hasnt been an update in almost a year.

**Comment by Miepee** [comment]
should be fixed with the merge of https://github.com/Alcaro/Flips/issues/62

**Comment by Alcaro** [comment]
Agreed
