### ISSUE TITLE
Why git clone takes too much data? What's in profile/ folder?

### ISSUE THREAD

**Issue by DarkSamus669** [Alcaro/Flips#63]
Last time i cloned it was about 60mb.

**Comment by Alcaro** [comment]
Two ancient copies of Firefox. They're not executed; they're used to generate PGO data, for greater performance.

I wouldn't mind replacing them if I could find a smaller dataset that gives the same result, but even if I did, they'll be in the git history, and trying to remove things from git history is generally Not Recommended™ for public projects.

Also please use the Discussions tab for things like this.

**Comment by DarkSamus669** [comment]
@Alcaro Well, 60mb for source code is a big thing, you should remove it.
