### ISSUE TITLE
Use GTKFileChooserNative instead of GTKFileChooser

### ISSUE THREAD

**Issue by Miepee** [Alcaro/Flips#69]
The native variants make the GTK build nicer on Linux platforms, due to it using the filepicker/save of the system environment, rather than always using GTK.
I think this just involves changing the `gtk_file_chooser_dialog_new`  calls with `gtk_file_chooser_native_new`. Will probably try to do a PR for this.
May or may not need to change the #define GDK_VERSION_MIN_REQUIRED at the top of the file, not sure.

**Comment by Alcaro** [comment]
Flips has a custom filter that accepts only executable files, used for the Select Emulator button. The native one doesn't seem to support that.

But that's a pretty small loss; it's a rare button, and you'll usually navigate to /usr/bin or ~/bin or something where filtering out nonexecutable files doesn't really do anything.

On the plus side, respecting the user's file chooser preference, and possibly helping Flatpak support (IIRC Flips currently demands full filesystem access).

Certainly sounds like an improvement to me.

**Comment by Miepee** [comment]
I'll look out for that, thanks!
