### ISSUE TITLE
Clang warns about deprecated sprintf

### ISSUE THREAD

**Issue by Miepee** [Alcaro/Flips#74]
It suggests to use snprintf over sprintf due to security reasons. I'm not a cpp guy, so just opening this issue for completeness sake. Feel free to close this as invalid if you think its a non-issue.
https://github.com/Alcaro/Flips/actions/runs/9197615734/job/25298479967

**Comment by Alcaro** [comment]
let's see if I missed anything. I probably did.

**Comment by Miepee** [comment]
Nope, those warnings are all gone now.

**Comment by Alcaro** [comment]
I thought there'd be a sprintf or two on the Windows side that I forgot fixing. Apparently not.

(Well, there's a 'wsprintf redefined' warning, but that's easy to fix.)

**Comment by Miepee** [comment]
OH actually, not sure if its the same issue, but windows is complaining about redefinition for wsprintf:
https://github.com/Alcaro/Flips/actions/runs/9197842175/job/25299205951
