### ISSUE TITLE
MSVC: `strings.h` not found on Windows

### ISSUE THREAD

**Issue by Miepee** [Alcaro/Flips#76]
MSVC complains about this import:
https://github.com/Alcaro/Flips/blob/7a5d55cc6c97a6f13d137c46253bfe25fb7d2914/flips.h#L66

Out of my expertise to know what exactly is used from that import and what the workaround would be.

**Comment by Alcaro** [comment]
I don't know either. It's not part of the C++ standard, so it shouldn't be included in the CLI interface at all.

Let's just nuke it and see what happens.

**Comment by Miepee** [comment]
Now MVSC complains about this:
`D:/a/Flips/Flips/flips.cpp(904): error C3861: 'strcasecmp': identifier not found`
`D:/a/Flips/Flips/flips.cpp(1426): error C3861: 'strcasecmp': identifier not found`

**Comment by Alcaro** [comment]
oh right, that function isn't standard C++ either.

Ideally, I'd reimplement that function using only standard functions, but... eh, this is good enough.

**Comment by Alcaro** [comment]
_stalks your fork's actions panel_

> `flips-w32.obj : error LNK2019: unresolved external symbol __imp_CreateFontA referenced in function "struct HFONT__ * __cdecl try_create_font(char const *,int)" (?try_create_font@@YAPEAUHFONT__@@PEBDH@Z)`
> `flips-w32.obj : error LNK2019: unresolved external symbol __imp_GetStockObject referenced in function "__int64 __cdecl bpsdProgressWndProc(struct HWND__ *,unsigned int,unsigned __int64,__int64)" (?bpsdProgressWndProc@@YA_JPEAUHWND__@@I_K_J@Z)`
> `flips-w32.obj : error LNK2019: unresolved external symbol __imp_SelectObject referenced in function "__int64 __cdecl bpsdProgressWndProc(struct HWND__ *,unsigned int,unsigned __int64,__int64)" (?bpsdProgressWndProc@@YA_JPEAUHWND__@@I_K_J@Z)`

Those aren't bugs in Flips. They're because MSVC ignored the -lgdi32 -lcomdlg32 -lcomctl32 etc arguments.

You'll need to pass in the MSVC equivalent. I think it should be gdi32.lib comdlg32.lib comctl32.lib etc? Maybe you could set $env:CXX='cl.exe gdi32.lib comdlg32.lib comctl32.lib etc'?
