### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by virginviolet** [Alcaro/Flips#85]
I just wanted to say that I made a Chocolatey package for Flips.
So you can now install flips with `choco install flips`.
Cheers

Package page: [flips](https://community.chocolatey.org/packages/flips)

**Comment by Alcaro** [comment]
That beat-protocol-system tag is typoed. It's patch or patching or something.

I think the B is Binary in the BPS v1.0 spec. It did change to beat at some point, but Flips never upgraded past BPS v1.0. (BPS manifests are similarly outdated; BPS v1.0 says it's XML, newer says it's BML, Flips says XML. Not like it matters, nobody uses those manifests anyways, everyone just ships the manifest in the zip beside the patch.)

**Comment by virginviolet** [comment]
I found "beat protocol system" on Google somewhere.

There are some rivaling interpretations:
- [beat protocol system](https://www.google.com/search?q=%22beat+protocol+system%22+%22bps%22)
- [beat patching system](https://www.google.com/search?q=%22beat+patching+system%22)
- [binary patching system](https://www.google.com/search?q=%22binary+patching+system%22+%22bps%22)
- [binary patch system](https://www.google.com/search?q=%22binary+patch+system%22+%22bps%22)

I think you are wrong that it used to stand for Binary Patch(ing System).
Here is supposedly the specification for v1. Though the last modified date of the files are 2016, but that could have been changed when extracting the files. The specification doesn't say what the abbreviation is. It talks about "beat files".

The RomHacking.net page for [Beat v1](https://www.romhacking.net/utilities/893/) says "beat is the canonical tool for working with **beat-protocol files**." [emphasis added].
"About" window in [Beat v ](https://www.romhacking.net/utilities/893/) says "A binary patching tool for the beat file format".

Logically, if BPS is supposed to be a replacement for IPS, and IPS (allegedly) stands for "International Patching System", then you would think BPS stood for "Beat Patching System". But! I think I actually found the answer to the mystery.

The user manual for [Beat v01](https://github.com/virginviolet/beat) actually explains the abbreviations for the file extensions bps and bpm:
> Patches that encode the difference between two files use the .**bps** extension, short for "**beat patch - single** (file)"
> Patches that encode the difference between two folders full of files use the .**bpm** extension, sort for "**beat patch - multi** (file)"

[emphasis added]

I'll replace `beat-protocol-system` with `beat-patch`, I think, for the next version. I cannot change it until there's a new version.

**Comment by Alcaro** [comment]
I wouldn't pay any attention to the RHDN description. I don't know who wrote it, but I'm pretty sure it's not the beat/BPS author.

Nor would I pay much attention to beat either; it's not the first BPS patcher. There's an older tool, called simply bps; I believe it was renamed to beat at the same time as bpm was created.

Not sure if you can find it, though. The author has always been quite skeptical to internet archival, and such short words are hard to google.

Considering nothing else uses those tags, it doesn't really matter what you claim BPS expands to, just do whatever. Or simply delete the tags, I don't think anyone's gonna look for em.

**Comment by Europia79** [comment]
@Alcaro ...bro, you know i use that BPS Manifest feature :P

As far as Tags go, i would think that BPS, patching, & flips would be sufficient.
