### ISSUE TITLE
PowerShell script to remove registry keys

### ISSUE THREAD

**Issue by virginviolet** [Alcaro/Flips#86]
Since the program cannot remove file associations, I thought it might be worth mentioning this. For the [Chocolatey package](https://github.com/Alcaro/Flips/issues/85), I made a PowerShell script that removes registry keys and values associated with Flips, primarily file associations.

Windows only.

It removes file associations set up by the application through its settings menu, as well as any associations set up by the system through user actions (manually selecting flips.exe to open a specific file type).

You can run this script without using Chocolatey. Just download [removeregistrykeys.ps1](https://github.com/virginviolet/chocolatey-packages/blob/main/manual/flips/tools/removeregistrykeys.ps1) from my repo, open PowerShell in the script's directory then run
`.\removeregistrykeys.ps1 '<executable directory>'`
Replace `<executable directory>` with the full path to the executable directory (do not include the `<` and `>` signs). I would use backslashes between directories for the path, but it might work with forward slashes, I'm not sure.

The executable directory is required for removing friendly name MuiCache value. This is nothing dangerous. It will be recreated when you run the program.

**Comment by Alcaro** [comment]
Last time I tried, Windows offered deleting the file associations if the associated executable is removed (after spending a minute looking for the exe in other directories).

Since I distribute Flips as an exe, not with any installer, that's enough for me (the MuiCache can just stay, it does no harm). But yes, a proper Flips package should be more thorough.

(Not sure if you want me to distribute or link that script anywhere, or if this issue is just informational, and/or for other packagers and end users.)

**Comment by virginviolet** [comment]
The file associations become invisible, except in the registry, when the exe is gone. At least on current Windows.

I'm just pedantic, probably why I made that script. And my rationale for posting it here was that it might be useful for someone. Either for a user, or if you wanted to do something with it.

I wouldn't mind if you distribute or link to the script, but if I thought it was important, I would have said so and not closed the issue right away. You do what you think is best for your repository.

By the way, why have you hidden releases from the sidebar? My ADHD mind thought there weren't any builds published here. (Yes, there's a link in the readme, I see that now.)

**Comment by Alcaro** [comment]
Probably mostly because I forgot enabling them after merging the auto release CI script.

Fixed.
