### ISSUE TITLE
Add a 'write to stdout' mode

### ISSUE THREAD

**Issue by i30817** [Alcaro/Flips#9]
(and maybe a 'read from stdin' mode, though that one is not so important).

This is in order to not be forced to create tmp files. In my usecase i'm using flips to help create .dat files for RA. 

In these (variably huge) files i'd like to apply the patch to the rom and grab stdout in order to calculate the needed checksums without actually writing the file to disk at any time.

xdelta has something like that iirc:

https://github.com/jmacd/xdelta/blob/wiki/CommandLineSyntax.md 'use stdout'

Now that i think about stdin is (when supported) in linux indicated by a '-'. It's probably not very possible here because patchers need *two* input files (though it's totally possible in bash with process substitution, which is annoying).

**Comment by Alcaro** [comment]
If you want the crc32 from a BPS or UPS patch, read the last 12 bytes, they contain source crc32 then target crc32 (then the patch's own crc32, for whatever reason). Far faster than patching, and doesn't even need the source ROM present.

If you want IPS or another checksum, use /dev/stdout as output file. It currently fails on the GTK frontend (CLI works), but that's a bug. I'll fix it later today.

Not sure about Windows, and I no longer have the ability to test anything there. Do you need that, or is /dev/stdout enough?

**Comment by i30817** [comment]
On the contrary, i want the checksums of the *patched file*. And i don't want to write it out to disk. This is achievable by having a switch on the command to write to stdout (and suppress any normal stdout output that may exist).

**Comment by Alcaro** [comment]
The header skipper is SNES only, and applies to the 512-byte SMC headers on the input files, not the headers of the BPS patch itself. As far as any other patcher knows, it's a perfectly normal BPS patch that turns one unheadered ROM into another.

You can turn it off with --exact, but that's kinda pointless when applying. It's autodetected whether the patch is intended for a headered ROM.

**Comment by i30817** [comment]
Can i use a FIFO? I mean if i provide a FIFO (named or not) that 'exists' already as a 'file' to the output parameter of flips, does it write to it 'as is' or tries to remove it first and make a new file?

**Comment by i30817** [comment]
Ok i made it with a FIFO but i hit a funny bug. Well, bug for me, not so much for you.

My function to not write is a bit complex:
```

def get_checksums():
    hash_md5   = hashlib.md5()
    hash_sha1  = hashlib.sha1()
    hash_crc32 = 0
    size = 0

    buf = yield

    while len(buf) > 0:
        size += len(buf)
        hash_md5.update(buf)
        hash_sha1.update(buf)
        hash_crc32 = zlib.crc32(buf, hash_crc32)
        buf = yield

    crc = "{:08x}".format( hash_crc32 & 0xffffffff )
    md5 = hash_md5.hexdigest()
    sha1 = hash_sha1.hexdigest()
    print( (size, crc, md5, sha1) )

    yield (size, crc, md5, sha1)

def patch_producer(patch, source, generator_function):
    BLOCKSIZE = 2 ** 20
    
    flips = shutil.which("flips")
    if not flips:
        flips = shutil.which("flips", path=os.path.dirname(__file__))
    if not flips:
        raise Exception("flips not found")
    
    
    process = None
    next(generator_function)
    with named_pipes() as pipes:
        pipe = pipes[0]
        with subprocess.Popen([flips, "-a", patch, source, pipe ], 
                stdout=subprocess.DEVNULL, 
                stderr=subprocess.DEVNULL) as process:
            with open(pipe, 'rb') as fifo:
                bytes = fifo.read(BLOCKSIZE)
                while len(bytes) > 0:
                    generator_function.send(bytes)
                    bytes = fifo.read(BLOCKSIZE)
    
    #if a error occurred avoid writing bogus checksums
    if process.returncode != 0:
        raise Exception("error during patching")

    return generator_function.send([])
```

Anyway i hit the bug that the generator that is calculating the checksums and the size... is calculating it without the header for the SFC (snes files) patched by bps. Apparently many patch files try to add a header *after* the main file is written, leading to badness on the calculation of checksums and size (especially if the file is a FIFO with 0 size).

Can you change this or it's too troublesome?

**Comment by Alcaro** [comment]
I expected GFile to overwrite that, but testing reveals that it works. Unexpected, but sure, why not. (If it hadn't, I'd tell it to try writing with libc before GFile.)

CLI and Windows fronts will write to the intended target as well. Named pipe is probably your only option on Windows, there's no /dev/stdout there. (No, CONOUT$ doesn't count.)

If you apply an unheadered BPS to a headered SNES ROM, Flips will assume you want headered output, and will copy it unchanged from the source. In this case, the easiest fix would be applying to unheadered ROMs.

If you've got an IPS that turns a headered source into a headered target, you have to give Flips a headered input, or you'll get a corrupt file. IPS patches don't contain any information about which file it's for, so Flips just assumes the input is correct.

If you've got an IPS that turns an unheadered source into a headered target (I've seen a few of those), Flips is emitting the correct target file, and I'm not changing that. You'll have to remove the header after patching.

If the inputs are FIFOs too, Flips won't like that, size+read is way easier than looping a read and reallocating until EOF. Especially when I have to do it thrice (GTK, Windows, libc). I'd accept a PR, but I'm not doing it myself.

If you're trying to ask anything else, please clarify. Is Flips writing the SMC header after the actual ROM contents?

**Comment by Alcaro** [comment]
Neat tools. Yeah, the extreme simplicity of IPS is useful sometimes. That specific operation seems a little too rare (and too different from existing operations) to include in Flips, but keeping it as a separate tool is a good idea.

> #(except for SNES headers, which is the one header bps ignores when creating/applying a patch)

Floating IPS drops SNES headers. The BPS spec itself does not demand such a thing, and other BPS creators leave headers alone. I'd prefer if I could remove that feature, it is a pretty ugly hack, but I had to make that compromise for the SMW hacking scene to switch from BPS.

Either way, if that tool exists, I'll just assume you're happy with how stderr/fifos work.

**Comment by i30817** [comment]
Yeah i'm happy now that i'm using FIFOs. I made a page for it:
https://github.com/i30817/rhdndat

BTW, there is another '512 bytes' header situation  on another hacking scene, but it's mostly with IPS, don't know how BPS would react. It's turbograph 16 / Pc-Engine patches.
